import restful.RestfulWebApi;
import util.FileRequest;
import util.HttpRequest;
import util.IRequest;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
       // IRequest req = new FileRequest();
        IRequest req = new HttpRequest();
        RestfulWebApi api= new RestfulWebApi(req);
        api.search("hee");


    }
}
